#!/bin/bash

# TODO remove this after testing fresh install
# sudo apt install autoconf autogen libasound2-dev libtool unzip

# wget "http://msp.ucsd.edu/Software/pd-0.50-2.src.tar.gz"
# tar -xvzf pd-0.50-2.src.tar.gz
# cd pd-0.50-2
# ./autogen.sh
# ./configure
# make
# sudo make install
# cd ..
# rm -r pd-*

apt install puredata

wget "https://marcobaumgartner.com/puredata/ALFALOOP/download/ALFALOOP_0.1.3.zip"
unzip ALFALOOP_0.1.3.zip
rm -r ALFALOOP_0.1.3.zip

sudo cp rc.local /etc/rc.local
